complete -c nixfmt -f -a '(__fish_complete_suffix .nix)'
complete -c nixfmt -s w -l width -x -d 'Maximum width in characters'
complete -c nixfmt -l indent -x -d 'Number of spaces for indentation'
complete -c nixfmt -s c -l check -d 'Check whether files are formatted'
complete -c nixfmt -s m -l mergetool -d 'Git mergetool mode'
complete -c nixfmt -s q -l quiet -d 'Do not report errors'
complete -c nixfmt -s s -l strict -d 'Enable stricter formatting mode'
complete -c nixfmt -s v -l verify -d 'Sanity-check output after formatting'
complete -c nixfmt -s a -l ast -d 'Dump internal AST to stderr'
complete -c nixfmt -l ir -d 'Dump internal IR to stderr'
complete -c nixfmt -s f -l filename -r -d 'Display name for stdin input'
complete -c nixfmt -l message-format -x -a 'human json' -d 'Diagnostic output format'
complete -c nixfmt -s h -l help -d 'Show help'
complete -c nixfmt -s V -l version -d 'Print version'
complete -c nixfmt -l numeric-version -d 'Print just the version number'
